version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/standalone"
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/cmssw"
    schedule:
      interval: "weekly"